### PR TITLE
Release/v0.0.7

### PR DESCRIPTION
**Pull request by Bachibouzouk**
This release would be needed to resolve https://github.com/openego/ego.io/issues/81

### CODE REVIEW

**Comment by MGlauer** [comment]
I will include this in the next release (0.0.7)

**Comment by Bachibouzouk** [comment]
> I will include this in the next release (0.0.7)

Where is the v0.0.6 release?

**Comment by MGlauer** [comment]
[Hera](https://github.com/OpenEnergyPlatform/oedialect/releases/tag/0.0.6). Sorry, I was not awary you were working on the dialect

**Comment by MGlauer** [comment]
And [on Pypi](https://pypi.org/project/oedialect/)

**Comment by Bachibouzouk** [comment]
> [Here](https://github.com/OpenEnergyPlatform/oedialect/releases/tag/0.0.6). Sorry, I was not awary you were working on the dialect

No problem, I should have explicitly tagged you in the egoio issue :)

**Comment by Bachibouzouk** [comment]
The changelog is added in this other PR : #23 , therefore this PR will be closed and its branch deleted.

**Pull request closed without merging**
